
languages:
   Ruby: true
   JavaScript: false
   Python: false
   PHP: false

engines:
  rubocop:
    enabled: true
    channel: rubocop-0-54

exclude_paths:
 - "lib/tasks/*"
 - "script/*"
 - "db//*/*"
 - "vendor//*/*"
 - "bin/*"
 - "log/*"
 - "public//*/*"
 - "coverage//*/*"
 - "doc//*/*"




