
languages:
   Ruby: true
   JavaScript: false
   Python: false
   PHP: false

exclude_paths:
 - "lib/tasks/*"
 - "script/*"
 - "db//*/*"
 - "vendor//*/*"
 - "bin/*"
 - "log/*"
 - "public//*/*"
 - "coverage//*/*"
 - "doc//*/*"




