# frozen_string_literal: true

# This module contains all application constants
module AppConstants
  # Alexa Skill Invocation Name e.g. ask fibro friend
  INVOCATION_NAME = 'fibro friend'
  # Alexa Skill Log file name
  LOG_FILE = '/log/fibro.log'
  # Alexa Skill ID
  SKILL_ID = 'amzn1.ask.skill.2c4d77ce-6d4e-4954-a5b5-fb8b6c12fb9d'
  # Folder for Alexa speech assets generated by our Interaction Model Builder
  SPEECH_FOLDER = 'app/speech_assets/files'
end
